spring.application.name=carbontrace

spring.datasource.url=jdbc:mysql://manoj.cpu8ymuom0xz.ap-south-1.rds.amazonaws.com:3306/carbontrace
spring.datasource.username=root
spring.datasource.password=Praveena15

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
